Feature: A new user can create new tip

  Scenario: tip creation is successful with video tip
    Given command new tip is selected
    When ...
    Then ...

  Scenario: tip creation is successful with book tip
    Given command new tip is selected
    When ...
    Then ...

  Scenario: tip creation is successful with podcast tip
    Given command new tip is selected
    When ...
    Then ...

  Scenario: tip creation is successful with blogpost tip
    Given command new tip is selected
    When ...
    Then ...
